---
language: rust
rust:
  - stable
  - nightly

script:
  # Run tests with thread based runtime
  - cargo test

  # Run tests with generator based runtime
  - cargo test --tests --features generator

  # Check with serde based checkpoint feature
  - cargo check --features checkpoint

notifications:
  email:
    on_success: never
