[package]
name = "loom"
# When releasing to crates.io:
# - Update version number
#   - lib.rs: html_root_url.
#   - README.md
# - Update CHANGELOG.md
# - Update doc URL.
#   - Cargo.toml
#   - README.md
# - Create git tag
version = "0.2.7"
edition = "2018"
license = "MIT"
authors = ["Carl Lerche <me@carllerche.com>"]
description = "Permutation testing for concurrent code"
documentation = "https://docs.rs/loom/0.2.7/loom"
homepage = "https://github.com/carllerche/loom"
repository = "https://github.com/carllerche/loom"
readme = "README.md"
keywords = ["atomic", "lock-free"]
categories = ["concurrency", "data-structures"]

[features]
default = []
checkpoint = ["serde", "serde_json"]
futures = ["futures-util-preview"]

[dependencies]
cfg-if = "0.1.6"
scoped-tls = "0.1.2"

# Provides a generator based runtime
generator = "0.6.18"

# Requires for "checkpoint" feature
serde = { version = "1.0.92", features = ["derive"], optional = true }
serde_json = { version = "1.0.33", optional = true }

futures-util-preview = { version = "=0.3.0-alpha.18", optional = true }
