[package]
name = "loom"
# When releasing to crates.io:
# - Update version number
#   - lib.rs: html_root_url.
#   - README.md
# - Update CHANGELOG.md
# - Update doc URL.
#   - Cargo.toml
#   - README.md
# - Create git tag
version = "0.2.0"
edition = "2018"
license = "MIT"
authors = ["Carl Lerche <me@carllerche.com>"]
description = "Model checker for concurrent code"
documentation = "https://docs.rs/loom/0.1.1/loom"
homepage = "https://github.com/carllerche/loom"
repository = "https://github.com/carllerche/loom"
readme = "README.md"
keywords = ["atomic", "lock-free"]
categories = ["concurrency", "data-structures"]
publish = false

[features]
default = []
checkpoint = ["serde", "serde_json"]

[dependencies]
cfg-if = "0.1.6"
# libc = "0.2.44"
scoped-tls = "0.1.2"

# Provides a generator based runtime
generator = "0.6.16"

# Optional futures support
futures = { version = "0.1.25", optional = true }

# Requires for "checkpoint" feature
serde = { version = "1.0.92", features = ["derive"], optional = true }
serde_json = { version = "1.0.33", optional = true }
